export const db = [
	{
		id: crypto.randomUUID(),
		firstName: "John",
		lastName: "Smith",
		birthday: "1990-01-01",
		avatar: "C:\\fakepath\\male.jpg",
		gender: "male",
		color: "#671e1e",
		season: "summer",
		continent: ["africa"],
		ocean: "atlantic",
		number: 3,
		vocation: "2023-06",
		languages: ["english"],
		login: "a",
		email: "john@gmail.com",
		password: "a",
		repeatPassword: "a",
	},
	{
		id: crypto.randomUUID(),
		firstName: "Jane",
		lastName: "Doe",
		birthday: "1996-07-09",
		avatar: "C:\\fakepath\\female.jpg",
		gender: "male",
		color: "#12ABA8",
		season: "autumn",
		continent: ["asia", "europe"],
		ocean: "indian",
		number: 3,
		vocation: "2022-08",
		languages: ["en", "ru"],
		login: "b",
		email: "jane@gmail.com",
		password: "b",
		repeatPassword: "b",
	},
];
